### ISSUE TITLE
frontend/backend interaction research

### ISSUE THREAD

**Issue by Trypt-Up** [EECE3093C/team-project-the-b-team-backend#13]

**Comment by nickyd3438** [comment]
Backend development: The backend developer will create the server-side code for the application, which includes data storage, security, and application logic. They will also create APIs that will enable the frontend developer to retrieve data from the server.

Frontend development: The frontend developer will create the client-side code for the application. This includes the user interface, which the user will interact with. They'll also use the APIs created by the backend developer to retrieve data from the server and display it on the user interface.
