### ISSUE TITLE
Team Meeting 3/1/2023 (11:07AM-12:50PM)

### ISSUE THREAD

**Issue by nickyd3438** [EECE3093C/team-project-the-b-team-backend#16]
Document team meeting notes in markdown for future reference.

**Comment by Trypt-Up** [comment]
The team discussed what we had researched so far and the best way to proceed. We are planning to meet/touch base 2-3 times a week in person going forward. I (Scott) am planning to create a bare-bones front end with minimal UI/UX that is able to store user data/inputs for future use of the backend and frontend. Abdullah and Nick are going to be working on the database and backend, respectively. Ideally, we would have some level of interaction between the components at the end of these three weeks, but that is not necessarily in the scope of this sprint.

**Comment by nickyd3438** [comment]
Another discussion we had is the work load going forward and that the back end will likely have more work to do than the front and that we would gauge the workload of each team member to see where the resources are best spent.
